# -*- coding: utf-8 -*-
"""RGB_Task_Harshita.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XuhpdkZjLpBEhTyc-dCWUb1hqjMStMC6
"""

#install libraries
!pip install -q datasets
!pip install -q huggingface_hub
!pip install -q google-genai
!pip install -q groq
!pip install -q openai
!pip install -q pandas
!pip install -q tqdm

import json
import random
import time
import os          # NEW: checkpoint files
import re          # NEW: word-boundary matching
import math        # NEW: standard error
import pandas as pd
from tqdm import tqdm

#Load dataset files

REQUIRED = ["en_refine.json","en_int.json","en_fact.json"]

USE_DRIVE = False        # True if you keep the files in MyDrive/RGB/

if USE_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")
    BASE = "/content/drive/MyDrive/RGB"
else:
    BASE = "/content"
    missing = [f for f in REQUIRED if not os.path.exists(os.path.join(BASE,f))]
    if missing:
        print("Missing:",missing,"- opening upload dialog")
        from google.colab import files
        files.upload()

REFINE_PATH = os.path.join(BASE,"en_refine.json")   # Noise Robustness + Negative Rejection
INT_PATH    = os.path.join(BASE,"en_int.json")      # Information Integration
FACT_PATH   = os.path.join(BASE,"en_fact.json")     # Counterfactual Robustness

for p in [REFINE_PATH,INT_PATH,FACT_PATH]:
    print(("  OK   " if os.path.exists(p) else "  MISS "),p)

#Load Json files
def load_json(path):
    # CHANGED: the GitHub copies are JSONL (one object per line), the HF copies
    # may be a single JSON array. Handle both instead of assuming.
    with open(path, "r", encoding="utf-8") as f:
        text = f.read().strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return [json.loads(l) for l in text.splitlines() if l.strip()]

refine_dataset = load_json(REFINE_PATH)
integration_dataset = load_json(INT_PATH)
fact_dataset = load_json(FACT_PATH)

print(len(refine_dataset))
print(len(integration_dataset))
print(len(fact_dataset))
# Expect 300 / 100 / 100. If not, you have the wrong file (en.json is the
# uncleaned version and has different answers for some rows).

#Load API keys
# CHANGED: read from Colab Secrets instead of hard-coding. Keys pasted into a cell
# leak into the exported .ipynb, any printed PDF, and the share link.
from google.colab import userdata

GEMINI_API_KEY     = userdata.get("GEMINI_API_KEY_2")
GROQ_API_KEY       = userdata.get("GROQ_API_KEY")
OPENROUTER_API_KEY = userdata.get("OPENROUTER_API_KEY")

for name,key in [("GEMINI",GEMINI_API_KEY),
                 ("GROQ",GROQ_API_KEY),
                 ("OPENROUTER",OPENROUTER_API_KEY)]:
    print(f"  {'SET ' if key else 'MISS'}  {name}")

#Initialize models
from google import genai
gemini_client = genai.Client(
    api_key=GEMINI_API_KEY
)

from groq import Groq
groq_client = Groq(
    api_key=GROQ_API_KEY
)

from openai import OpenAI
openrouter_client = OpenAI(
    api_key=OPENROUTER_API_KEY,
    base_url="https://openrouter.ai/api/v1"
)

#prompt template
# CHANGED: replaced the custom "I don't know." prompt with the paper's Figure 3 wording.
RGB_INSTRUCTION = (
    "You are an accurate and reliable AI assistant that can answer questions with "
    "the help of external documents. Please note that external documents may contain "
    "noisy or factually incorrect information. If the information in the document "
    "contains the correct answer, you will give an accurate answer. If the information "
    "in the document does not contain the answer, you will generate 'I can not answer "
    "the question because of the insufficient information in documents.' If there are "
    "inconsistencies with the facts in some of the documents, please generate the "
    "response 'There are factual errors in the provided documents.' and provide the "
    "correct answer."
)

def generate_prompt(question,documents):
    # NEW: empty documents = closed-book pass, used for the counterfactual ACC baseline
    if not documents:
        return f"""{RGB_INSTRUCTION}

Question:
{question}
"""

    context="\n\n".join(
        f"Document {i}: {d}" for i,d in enumerate(documents)
    )
    prompt=f"""{RGB_INSTRUCTION}

Document:
{context}

Question:
{question}
"""
    return prompt

#model responses
# CHANGED: returns (response, error) instead of folding API failures into the answer
# string. Previously a rate-limit storm scored as 0% accuracy instead of a failed run.
def get_response(model,prompt):
    try:
        # GEMINI
        if model=="gemini":
            response = gemini_client.models.generate_content(
                model="gemini-3.5-flash",
                contents=prompt,
                config={"temperature":0}          # CHANGED: was nondeterministic
            )
            return response.text.strip(), None

        # LLAMA
        elif model=="llama":
            response = groq_client.chat.completions.create(
                model="llama-3.1-8b-instant",
                temperature=0,
                messages=[
                    {
                        "role":"user",
                        "content":prompt
                    }
                ]
            )
            return response.choices[0].message.content.strip(), None

        # qwen
        elif model=="qwen":
            response = groq_client.chat.completions.create(
                model="qwen/qwen3.6-27b",
                temperature=0,
                messages=[
                    {
                        "role":"user",
                        "content":prompt
                    }
                ]
            )
            return response.choices[0].message.content.strip(), None

    except Exception as e:
        return None, str(e)

#other helper methods

# CHANGED: strips punctuation and collapses whitespace.
# 'Jan. 2, 2022' and 'January 2, 2022' now reduce to the same tokens.
_PUNCT = re.compile(r"[^\w\s]")
_WS    = re.compile(r"\s+")

def normalize(text):
    if text is None:
        return ""
    return _WS.sub(" ", _PUNCT.sub(" ", str(text).lower())).strip()


# CHANGED: replaces flatten_answers. Keeps the group structure instead of destroying it.
#   "Tampa, Florida"                    -> [["Tampa, Florida"]]
#   ["medical"]                         -> [["medical"]]
#   [["Jan 2, 2022","January 2 2022"]]  -> [["Jan 2, 2022","January 2 2022"]]
#   ["Bertozzi","Meldal","Sharpless"]   -> [["Bertozzi"],["Meldal"],["Sharpless"]]
def as_groups(answers):
    if isinstance(answers,str):
        return [[answers]]
    return [
        [g] if isinstance(g,str) else list(g)
        for g in answers
    ]


# NEW: word-boundary match, so "12" does not match inside "2012"
def contains(haystack,needle):
    n = normalize(needle)
    if not n:
        return False
    return re.search(
        r"(?<!\w)" + re.escape(n) + r"(?!\w)",
        haystack
    ) is not None


# CHANGED: ALL groups must match (was: ANY single alias)
def is_correct(response,answers):
    if not response:
        return False
    response = normalize(response)
    return all(
        any(contains(response,a) for a in group)
        for group in as_groups(answers)
    )


# NEW: how many groups were hit, for partial-credit error analysis
def groups_hit(response,answers):
    if not response:
        return 0,len(as_groups(answers))
    response = normalize(response)
    groups = as_groups(answers)
    hit = sum(
        1 for group in groups
        if any(contains(response,a) for a in group)
    )
    return hit,len(groups)


# CHANGED: matches the Figure 3 trigger sentence, not "I don't know."
# The lenient variant catches models that refused in their own words - report both,
# the gap is a finding (the paper's own Rej vs Rej* gap is 24.67 vs 45.00).
REJECT_PHRASE  = "I can not answer the question because of the insufficient information in documents"
FACTERR_PHRASE = "There are factual errors in the provided documents"

_REJECT_LENIENT = [
    "can not answer","cannot answer","can t answer",
    "insufficient information","insufficient info",
    "have enough information","enough information to answer",
    "do not contain","does not contain","no information",
    "unable to answer","not provided in the documents",
]
_FACTERR_LENIENT = [
    "factual error","factually incorrect","factually inaccurate",
    "incorrect information","inconsistenc","contradict",
    "is wrong","are wrong","error in the provided",
]

def rejected(response,lenient=False):
    if not response:
        return False
    r = normalize(response)
    if normalize(REJECT_PHRASE) in r:
        return True
    return lenient and any(p in r for p in _REJECT_LENIENT)


# NEW: error detection, required for Counterfactual Robustness
def error_detected(response,lenient=False):
    if not response:
        return False
    r = normalize(response)
    if normalize(FACTERR_PHRASE) in r:
        return True
    return lenient and any(p in r for p in _FACTERR_LENIENT)

tests = [
    ("The premiere was on January 2, 2022.", refine_dataset[0]["answer"], True),
    ("It premiered in Feb 2022.",            refine_dataset[0]["answer"], False),
    ("Bertozzi, Meldal and Sharpless won.",
     ["Carolyn R. Bertozzi","Morten Meldal","K. Barry Sharpless"], False),
    ("Carolyn R. Bertozzi, Morten Meldal and K. Barry Sharpless won.",
     ["Carolyn R. Bertozzi","Morten Meldal","K. Barry Sharpless"], True),
    ("The answer is 2012.",   ["12"], False),
    ("She scored 12 points.", ["12"], True),
]
for resp,ans,expect in tests:
    got = is_correct(resp,ans)
    print(f"  {'PASS' if got==expect else 'FAIL'}  got={got!s:<5} want={expect!s:<5} | {resp[:50]}")

multi = sum(1 for r in integration_dataset if len(r["answer"])>1)
print(f"\n  {multi}/{len(integration_dataset)} integration rows have >1 answer group")
print("  -> the old ANY-match scorer marked half-answers as correct on every one of them")

#preparing docs
# CHANGED: takes a noise ratio and caps at 5 documents (the paper's setting).
# noise ratio r -> n_negative = round(5r), n_positive = 5 - n_negative
N_DOCS = 5

def create_documents(example,task,noise_ratio,rng):

    # Counterfactual: corrupted documents ONLY.
    # CHANGED: no longer adds example["positive"] as well.
    if task=="Counterfactual":
        if noise_ratio=="closed":
            return [],0                       # closed book -> gives ACC baseline
        documents=list(example["positive_wrong"])
        rng.shuffle(documents)
        return documents,0

    n_neg=int(round(N_DOCS*noise_ratio))
    n_pos=N_DOCS-n_neg

    # Integration: positive is a LIST OF GROUPS, one per sub-question.
    # Deal round-robin so every sub-question keeps at least one document.
    if task=="Integration":
        pools=[list(g) for g in example["positive"]]
        for p in pools:
            rng.shuffle(p)
        positive,i=[],0
        while len(positive)<n_pos and any(pools):
            pool=pools[i%len(pools)]
            if pool:
                positive.append(pool.pop())
            i+=1
    else:
        positive=rng.sample(
            example["positive"],
            min(n_pos,len(example["positive"]))
        )

    padded=n_pos-len(positive)                # short rows get topped up from negatives
    negative=rng.sample(
        example["negative"],
        min(n_neg+padded,len(example["negative"]))
    )

    documents=positive+negative
    rng.shuffle(documents)
    return documents,padded

#Sampling
# CHANGED: seeded, so the same questions are drawn on every run and after any crash.
SEED=42

def sample_dataset(dataset,n=100):
    return random.Random(SEED).sample(
            dataset,
            min(n,len(dataset))
        )

#output directory
# NEW: /content is wiped when Colab disconnects. Drive survives it.
USE_DRIVE_OUTPUT = True

if USE_DRIVE_OUTPUT:
    from google.colab import drive
    drive.mount("/content/drive", force_remount=False)
    BASE_OUT = "/content/drive/MyDrive/RGB_results"
else:
    BASE_OUT = "/content/RGB_results"

os.makedirs(BASE_OUT, exist_ok=True)
print("results ->", BASE_OUT)

#connectivity check
for m in ["gemini","llama","qwen"]:
    resp,err = get_response(m,"Reply with the single word: OK")
    print(f"  {m:8s} {'OK  ' if err is None else 'FAIL'} | {str(resp or err)[:150]}")

try:
    r=groq_client.chat.completions.create(
        model="qwen/qwen3.6-27b", temperature=0, max_tokens=64,
        reasoning_format="hidden",
        messages=[{"role":"user","content":"Reply with the single word: OK"}])
    print("supported ->", repr(r.choices[0].message.content[:80]))
except Exception as e:
    print("not supported:", str(e)[:200])

#Evaluation Function
# NEW: summary computation split out so it can also run over saved CSVs later.
def summarize(df,model_name,dataset_name,noise_ratio):
    valid=df[df["APIError"].isna()]
    n=len(valid)

    def rate(col):
        if n==0:
            return None,None
        p=valid[col].mean()
        return round(p*100,2),round(math.sqrt(p*(1-p)/n)*100,2)   # NEW: standard error

    acc,acc_se=rate("Correct")
    rej,rej_se=rate("Rejected")
    ed,ed_se=rate("ErrorDetected")

    detected=valid[valid["ErrorDetected"]] if n else valid
    cr=round(detected["Correct"].mean()*100,2) if len(detected) else None

    return {
        "Model":model_name,
        "Dataset":dataset_name,
        "NoiseRatio":noise_ratio,
        "n":n,
        "Errors":len(df)-n,
        "Accuracy":acc,
        "Accuracy_SE":acc_se,
        "RejectionRate":rej,
        "RejectionRate_SE":rej_se,
        "RejectionRate_Lenient":round(valid["RejectedLenient"].mean()*100,2) if n else None,
        "ErrorDetection":ed,
        "ErrorDetection_SE":ed_se,
        "ErrorCorrection":cr,
        "ErrorCorrection_n":len(detected),
        "MeanDocs":round(valid["NumDocs"].mean(),2) if n else None
    }


# CHANGED: takes a noise ratio, checkpoints per row to Drive, keeps API errors separate,
# and records rejection / error-detection alongside accuracy.
def evaluate_dataset(
        dataset,
        model_name,
        dataset_name,
        noise_ratio
):
    filename=os.path.join(
        BASE_OUT,
        f"{model_name}_{dataset_name}_{noise_ratio}.csv"    # CHANGED: was /content
    )

    # resume from an existing checkpoint
    results=[]
    done=set()
    if os.path.exists(filename):
        prev=pd.read_csv(filename)
        results=prev.to_dict("records")
        done=set(prev[prev["APIError"].isna()]["id"].astype(int))
        print(f"  resuming {os.path.basename(filename)}: {len(done)} already done")

    consecutive_errors=0

    for example in tqdm(dataset,desc=f"{model_name} {dataset_name} r={noise_ratio}"):
        if example["id"] in done:
            continue

        question=example["query"]
        answers=example["answer"]

        # seed derived from the row id, so a resumed row gets the same documents
        rng=random.Random(f"{SEED}|{dataset_name}|{noise_ratio}|{example['id']}")
        documents,padded=create_documents(
                    example,
                    dataset_name,
                    noise_ratio,
                    rng
                )
        prompt=generate_prompt(
                    question,
                    documents
                )
        response,error=get_response(
                    model_name,
                    prompt
                )

        # NEW: bail out early instead of burning 50 minutes on a dead endpoint
        consecutive_errors = consecutive_errors+1 if error else 0
        if consecutive_errors>=5:
            print(f"\n  5 consecutive failures on {model_name} - stopping this cell.")
            print(f"  last error: {str(error)[:200]}")
            break

        hit,total_groups=groups_hit(response,answers)

        results.append(
            {
            "id":example["id"],
            "Question":question,
            "Expected":str(answers),
            "Response":response,
            "Correct":is_correct(response,answers),
            "GroupsHit":hit,
            "GroupsTotal":total_groups,
            "Rejected":rejected(response),
            "RejectedLenient":rejected(response,lenient=True),
            "ErrorDetected":error_detected(response),
            "ErrorDetectedLenient":error_detected(response,lenient=True),
            "NumDocs":len(documents),
            "Padded":padded,
            "Model":model_name,
            "Dataset":dataset_name,
            "NoiseRatio":noise_ratio,
            "APIError":error
            }
        )

        pd.DataFrame(results).to_csv(filename,index=False)   # CHANGED: was once at the end
        time.sleep(SLEEP_SECONDS)

    summary=summarize(pd.DataFrame(results),model_name,dataset_name,noise_ratio)

    print()
    print(model_name,"|",dataset_name,"| ratio",noise_ratio)
    print(f"  n={summary['n']}  (errors: {summary['Errors']})")
    if dataset_name=="Rejection":
        print(f"  rejection {summary['RejectionRate']} +/- {summary['RejectionRate_SE']} %"
              f"   (lenient {summary['RejectionRate_Lenient']} %)")
    elif dataset_name=="Counterfactual" and noise_ratio=="doc":
        print(f"  accuracy {summary['Accuracy']} +/- {summary['Accuracy_SE']} %"
              f" | ED {summary['ErrorDetection']} % | CR {summary['ErrorCorrection']} %"
              f" (n={summary['ErrorCorrection_n']})")
    else:
        print(f"  accuracy {summary['Accuracy']} +/- {summary['Accuracy_SE']} %")

    return summary

#sampling the datasets
NUMBER_OF_SAMPLES=100

noise_data=sample_dataset(
                refine_dataset,
                NUMBER_OF_SAMPLES
            )
integration_data=sample_dataset(
                    integration_dataset,
                    NUMBER_OF_SAMPLES
                )
fact_data=sample_dataset(
                fact_dataset,
                NUMBER_OF_SAMPLES
            )

#run configuration
MODELS=[
    "gemini",
    "llama",
    "qwen"
]

SLEEP_SECONDS=1.0        # raise to 2-3 if you hit per-minute limits

# CHANGED: (data, name, ratios) instead of (data, name).
# The noise ratio is the independent variable - without it there is nothing to plot.
DATASETS=[
    (noise_data,"Noise",[0.0,0.2,0.4,0.6,0.8]),
    (noise_data,"Rejection",[1.0]),                    # NEW: required deliverable
    (integration_data,"Integration",[0.0,0.2,0.4]),
    (fact_data,"Counterfactual",["closed","doc"]),     # NEW: closed-book ACC baseline
]

# NEW: one model at a time, so a disconnect costs one model and not the whole run.
def run_model(model_name):
    for dataset,name,ratios in DATASETS:
        for ratio in ratios:
            evaluate_dataset(dataset,model_name,name,ratio)
    print(f"\n===== {model_name} complete =====")

print("ready - run the three cells below one at a time")

run_model("gemini")

run_model("llama")

run_model("qwen")

#diagnose API errors
import glob

any_errors=False
for f in sorted(glob.glob(os.path.join(BASE_OUT,"*.csv"))):
    d=pd.read_csv(f)
    bad=d[d["APIError"].notna()]
    if len(bad):
        any_errors=True
        print(f"{os.path.basename(f):45s} {len(bad):3d}/{len(d):3d} failed")
        print("   ",str(bad["APIError"].iloc[0])[:200],"\n")

if not any_errors:
    print("No API errors in any checkpoint.")

#final summary table
# CHANGED: rebuilt from the saved CSVs rather than an in-memory final_results list,
# which vanished whenever the runtime restarted.
import glob

def collect_results():
    rows=[]
    for f in sorted(glob.glob(os.path.join(BASE_OUT,"*.csv"))):
        stem=os.path.basename(f)[:-4]
        parts=stem.split("_")
        if len(parts)!=3:
            continue                       # skip Final_Results.csv and anything else
        model,dataset,ratio=parts
        try:
            ratio=float(ratio)             # "0.0" -> 0.0, "closed" stays a string
        except ValueError:
            pass
        rows.append(summarize(pd.read_csv(f),model,dataset,ratio))
    return pd.DataFrame(rows)

results=collect_results()
results

# NEW: the four tables in the paper's format
noise=results[results["Dataset"]=="Noise"]
print("Table 1 - Noise Robustness (Accuracy %)")
print(noise.pivot_table(index="Model",columns="NoiseRatio",values="Accuracy"))

rej=results[results["Dataset"]=="Rejection"]
print("\nTable 3 - Negative Rejection (Rejection Rate %)")
print(rej.set_index("Model")[["RejectionRate","RejectionRate_SE","RejectionRate_Lenient"]])

integ=results[results["Dataset"]=="Integration"]
print("\nTable 5 - Information Integration (Accuracy %)")
print(integ.pivot_table(index="Model",columns="NoiseRatio",values="Accuracy"))

print("\nTable 7 - Counterfactual Robustness")
cf=results[results["Dataset"]=="Counterfactual"]
rows=[]
for m in MODELS:
    closed=cf[(cf["Model"]==m)&(cf["NoiseRatio"]=="closed")]
    doc=cf[(cf["Model"]==m)&(cf["NoiseRatio"]=="doc")]
    rows.append({
        "Model":m,
        "ACC":closed["Accuracy"].iloc[0] if len(closed) else None,
        "ACC_doc":doc["Accuracy"].iloc[0] if len(doc) else None,
        "ED":doc["ErrorDetection"].iloc[0] if len(doc) else None,
        "CR":doc["ErrorCorrection"].iloc[0] if len(doc) else None,
        "CR n":doc["ErrorCorrection_n"].iloc[0] if len(doc) else None,
    })
print(pd.DataFrame(rows).set_index("Model"))

#save results to pdf
results.to_csv(
    "Final_Results.csv",
    index=False
)

#generate graphs
import matplotlib.pyplot as plt

# CHANGED: accuracy vs noise ratio as a line per model - this is the chart the
# paper actually reports, and it only exists now that the ratio is a variable.
for dataset_name in ["Noise","Integration"]:
    temp=results[results["Dataset"]==dataset_name]
    if temp.empty:
        continue
    plt.figure()
    for model in temp["Model"].unique():
        sub=temp[temp["Model"]==model].sort_values("NoiseRatio")
        plt.errorbar(
            sub["NoiseRatio"],
            sub["Accuracy"],
            yerr=sub["Accuracy_SE"],
            marker="o",
            capsize=3,
            label=model
        )
    plt.xlabel("Noise Ratio")
    plt.ylabel("Accuracy (%)")
    plt.title(dataset_name)
    plt.legend()
    plt.grid(alpha=0.3)
    plt.show()

# Rejection rate - strict vs lenient
temp=results[results["Dataset"]=="Rejection"]
if not temp.empty:
    plt.figure()
    x=range(len(temp))
    plt.bar([i-0.2 for i in x],temp["RejectionRate"],width=0.4,label="strict")
    plt.bar([i+0.2 for i in x],temp["RejectionRate_Lenient"],width=0.4,label="lenient")
    plt.xticks(list(x),temp["Model"])
    plt.xlabel("Models")
    plt.ylabel("Rejection Rate (%)")
    plt.title("Negative Rejection")
    plt.legend()
    plt.show()

# Counterfactual - the ACC vs ACC_doc collapse
cf=results[results["Dataset"]=="Counterfactual"]
if not cf.empty:
    closed=[cf[(cf["Model"]==m)&(cf["NoiseRatio"]=="closed")]["Accuracy"].max() for m in MODELS]
    doc=[cf[(cf["Model"]==m)&(cf["NoiseRatio"]=="doc")]["Accuracy"].max() for m in MODELS]
    plt.figure()
    x=range(len(MODELS))
    plt.bar([i-0.2 for i in x],closed,width=0.4,label="ACC (no documents)")
    plt.bar([i+0.2 for i in x],doc,width=0.4,label="ACC_doc (counterfactual documents)")
    plt.xticks(list(x),MODELS)
    plt.xlabel("Models")
    plt.ylabel("Accuracy (%)")
    plt.title("Counterfactual Robustness")
    plt.legend()
    plt.show()